import { v4 as uuidv4 } from 'uuid'
import type {
  AppData,
  User,
  Site,
  Location,
  Ticket,
  Asset,
  WorkOrder,
  PMPlan,
  Supplier,
  RFQ,
  Quote,
  PO,
  ActivityEvent,
} from '../types'

const now = new Date()
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString()
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString()

export function generateDemoData(): AppData {
  // Users
  const users: User[] = [
    {
      id: uuidv4(),
      name: 'Sarah Chen',
      email: 'sarah.chen@demo.com',
      role: 'manager',
      createdAt: daysAgo(90),
    },
    {
      id: uuidv4(),
      name: 'Mike Rodriguez',
      email: 'mike.rodriguez@demo.com',
      role: 'technician',
      createdAt: daysAgo(85),
    },
    {
      id: uuidv4(),
      name: 'Emily Watson',
      email: 'emily.watson@demo.com',
      role: 'dispatcher',
      createdAt: daysAgo(80),
    },
    {
      id: uuidv4(),
      name: 'James Kim',
      email: 'james.kim@demo.com',
      role: 'requester',
      createdAt: daysAgo(70),
    },
    {
      id: uuidv4(),
      name: 'Lisa Anderson',
      email: 'lisa.anderson@demo.com',
      role: 'technician',
      createdAt: daysAgo(60),
    },
  ]

  // Sites across industries
  const sites: Site[] = [
    {
      id: uuidv4(),
      name: 'Downtown Manufacturing Plant',
      address: '123 Industrial Blvd',
      city: 'Detroit, MI',
      industry: 'Manufacturing',
      managerId: users[0].id,
      createdAt: daysAgo(100),
    },
    {
      id: uuidv4(),
      name: 'Medical Center East',
      address: '456 Healthcare Dr',
      city: 'Boston, MA',
      industry: 'Healthcare',
      managerId: users[0].id,
      createdAt: daysAgo(95),
    },
    {
      id: uuidv4(),
      name: 'Riverside Hotel & Conference',
      address: '789 Waterfront Ave',
      city: 'Seattle, WA',
      industry: 'Hospitality',
      managerId: users[0].id,
      createdAt: daysAgo(90),
    },
  ]

  // Locations
  const locations: Location[] = [
    // Manufacturing
    { id: uuidv4(), siteId: sites[0].id, name: 'Production Floor A', floor: '1', createdAt: daysAgo(100) },
    { id: uuidv4(), siteId: sites[0].id, name: 'Warehouse', floor: '1', createdAt: daysAgo(100) },
    { id: uuidv4(), siteId: sites[0].id, name: 'Quality Control Lab', floor: '2', createdAt: daysAgo(100) },
    // Healthcare
    { id: uuidv4(), siteId: sites[1].id, name: 'Emergency Department', floor: '1', createdAt: daysAgo(95) },
    { id: uuidv4(), siteId: sites[1].id, name: 'Operating Rooms', floor: '3', createdAt: daysAgo(95) },
    { id: uuidv4(), siteId: sites[1].id, name: 'Radiology', floor: '2', createdAt: daysAgo(95) },
    // Hospitality
    { id: uuidv4(), siteId: sites[2].id, name: 'Hotel Lobby', floor: '1', createdAt: daysAgo(90) },
    { id: uuidv4(), siteId: sites[2].id, name: 'Guest Rooms Floor 5', floor: '5', createdAt: daysAgo(90) },
    { id: uuidv4(), siteId: sites[2].id, name: 'Conference Center', floor: '2', createdAt: daysAgo(90) },
  ]

  // Assets
  const assets: Asset[] = [
    {
      id: uuidv4(),
      name: 'CNC Machine #3',
      assetTag: 'MFG-CNC-003',
      category: 'Production Equipment',
      siteId: sites[0].id,
      locationId: locations[0].id,
      status: 'operational',
      manufacturer: 'Haas Automation',
      model: 'VF-2',
      serialNumber: 'SN-45678',
      purchaseDate: daysAgo(730),
      qrCode: 'QR-MFG-CNC-003',
      createdAt: daysAgo(730),
      updatedAt: daysAgo(10),
    },
    {
      id: uuidv4(),
      name: 'Forklift Toyota 8FG25',
      assetTag: 'MFG-FKL-001',
      category: 'Material Handling',
      siteId: sites[0].id,
      locationId: locations[1].id,
      status: 'maintenance',
      manufacturer: 'Toyota',
      model: '8FG25',
      serialNumber: 'SN-89012',
      purchaseDate: daysAgo(1095),
      qrCode: 'QR-MFG-FKL-001',
      createdAt: daysAgo(1095),
      updatedAt: daysAgo(2),
    },
    {
      id: uuidv4(),
      name: 'MRI Scanner Siemens',
      assetTag: 'MED-MRI-001',
      category: 'Medical Imaging',
      siteId: sites[1].id,
      locationId: locations[5].id,
      status: 'operational',
      manufacturer: 'Siemens Healthineers',
      model: 'MAGNETOM Sola',
      serialNumber: 'SN-12345',
      purchaseDate: daysAgo(365),
      warrantyExpiry: daysFromNow(1095),
      qrCode: 'QR-MED-MRI-001',
      createdAt: daysAgo(365),
      updatedAt: daysAgo(5),
    },
    {
      id: uuidv4(),
      name: 'HVAC Unit - Rooftop #2',
      assetTag: 'HTL-HVAC-002',
      category: 'HVAC',
      siteId: sites[2].id,
      status: 'operational',
      manufacturer: 'Carrier',
      model: 'AquaEdge 19DV',
      serialNumber: 'SN-67890',
      purchaseDate: daysAgo(1460),
      qrCode: 'QR-HTL-HVAC-002',
      createdAt: daysAgo(1460),
      updatedAt: daysAgo(15),
    },
  ]

  // Tickets
  const tickets: Ticket[] = [
    {
      id: uuidv4(),
      title: 'CNC Machine error code E-245',
      description: 'Machine stops mid-cycle with error E-245. Need immediate attention.',
      category: 'maintenance',
      priority: 'high',
      status: 'in_progress',
      siteId: sites[0].id,
      locationId: locations[0].id,
      requesterId: users[3].id,
      assigneeId: users[1].id,
      dueDate: daysFromNow(1),
      slaDeadline: daysFromNow(1),
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0.5),
    },
    {
      id: uuidv4(),
      title: 'Forklift battery replacement needed',
      description: 'Battery not holding charge. Needs replacement.',
      category: 'maintenance',
      priority: 'medium',
      status: 'open',
      siteId: sites[0].id,
      locationId: locations[1].id,
      requesterId: users[3].id,
      dueDate: daysFromNow(3),
      slaDeadline: daysFromNow(3),
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: uuidv4(),
      title: 'OR suite lighting flickering',
      description: 'Lights in OR-3 are flickering intermittently. Safety concern.',
      category: 'facilities',
      priority: 'critical',
      status: 'open',
      siteId: sites[1].id,
      locationId: locations[4].id,
      requesterId: users[3].id,
      assigneeId: users[4].id,
      dueDate: daysFromNow(0.5),
      slaDeadline: daysFromNow(0.5),
      createdAt: daysAgo(0.2),
      updatedAt: daysAgo(0.2),
    },
    {
      id: uuidv4(),
      title: 'Guest room 512 AC not working',
      description: 'Room 512 reports AC unit not cooling. Urgent as guest is checking in tonight.',
      category: 'maintenance',
      priority: 'high',
      status: 'resolved',
      siteId: sites[2].id,
      locationId: locations[7].id,
      requesterId: users[3].id,
      assigneeId: users[1].id,
      dueDate: daysAgo(1),
      slaDeadline: daysAgo(1),
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
      resolvedAt: daysAgo(1),
    },
    {
      id: uuidv4(),
      title: 'Fire alarm inspection due',
      description: 'Annual fire alarm system inspection and testing required.',
      category: 'safety',
      priority: 'medium',
      status: 'open',
      siteId: sites[2].id,
      requesterId: users[0].id,
      dueDate: daysFromNow(7),
      slaDeadline: daysFromNow(7),
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
  ]

  // Work Orders
  const workOrders: WorkOrder[] = [
    {
      id: uuidv4(),
      title: 'PM - CNC Machine Maintenance',
      description: 'Monthly preventive maintenance for CNC Machine #3',
      type: 'preventive',
      status: 'completed',
      priority: 'medium',
      assetId: assets[0].id,
      siteId: sites[0].id,
      locationId: locations[0].id,
      assigneeId: users[1].id,
      scheduledDate: daysAgo(10),
      dueDate: daysAgo(10),
      checklist: [
        { id: uuidv4(), description: 'Check oil levels', completed: true, completedBy: users[1].id, completedAt: daysAgo(10) },
        { id: uuidv4(), description: 'Inspect belts and chains', completed: true, completedBy: users[1].id, completedAt: daysAgo(10) },
        { id: uuidv4(), description: 'Clean coolant system', completed: true, completedBy: users[1].id, completedAt: daysAgo(10) },
        { id: uuidv4(), description: 'Test emergency stop', completed: true, completedBy: users[1].id, completedAt: daysAgo(10) },
      ],
      partsUsed: [{ id: uuidv4(), name: 'Hydraulic Oil 5L', quantity: 1, unitCost: 45.0 }],
      laborHours: 2.5,
      completionNotes: 'All systems operational. Next PM due in 30 days.',
      createdAt: daysAgo(15),
      updatedAt: daysAgo(10),
      completedAt: daysAgo(10),
    },
    {
      id: uuidv4(),
      title: 'Repair - Forklift Battery Issue',
      description: 'Diagnose and repair battery charging issue',
      type: 'corrective',
      status: 'in_progress',
      priority: 'medium',
      assetId: assets[1].id,
      siteId: sites[0].id,
      locationId: locations[1].id,
      assigneeId: users[1].id,
      ticketId: tickets[1].id,
      scheduledDate: daysFromNow(1),
      dueDate: daysFromNow(3),
      checklist: [
        { id: uuidv4(), description: 'Test battery voltage', completed: true, completedBy: users[1].id, completedAt: daysAgo(1) },
        { id: uuidv4(), description: 'Check charging system', completed: true, completedBy: users[1].id, completedAt: daysAgo(1) },
        { id: uuidv4(), description: 'Replace battery if needed', completed: false },
      ],
      partsUsed: [],
      laborHours: 1.5,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ]

  // PM Plans
  const pmPlans: PMPlan[] = [
    {
      id: uuidv4(),
      name: 'CNC Machine Monthly PM',
      description: 'Monthly preventive maintenance schedule',
      assetId: assets[0].id,
      frequency: 'monthly',
      taskList: ['Check oil levels', 'Inspect belts', 'Clean coolant system', 'Test emergency stop'],
      assigneeId: users[1].id,
      isActive: true,
      lastPerformed: daysAgo(10),
      nextDue: daysFromNow(20),
      createdAt: daysAgo(730),
      updatedAt: daysAgo(10),
    },
    {
      id: uuidv4(),
      name: 'MRI Scanner Quarterly Inspection',
      description: 'Quarterly inspection and calibration',
      assetId: assets[2].id,
      frequency: 'quarterly',
      taskList: ['Calibration check', 'Coil inspection', 'Safety system test', 'Software updates'],
      assigneeId: users[4].id,
      isActive: true,
      lastPerformed: daysAgo(45),
      nextDue: daysFromNow(45),
      createdAt: daysAgo(365),
      updatedAt: daysAgo(45),
    },
    {
      id: uuidv4(),
      name: 'HVAC Filter Replacement',
      description: 'Monthly filter replacement and inspection',
      assetId: assets[3].id,
      frequency: 'monthly',
      taskList: ['Replace air filters', 'Check refrigerant levels', 'Inspect ductwork', 'Test thermostats'],
      assigneeId: users[1].id,
      isActive: true,
      lastPerformed: daysAgo(15),
      nextDue: daysFromNow(15),
      createdAt: daysAgo(1460),
      updatedAt: daysAgo(15),
    },
  ]

  // Suppliers
  const suppliers: Supplier[] = [
    {
      id: uuidv4(),
      name: 'Industrial Parts Supply Co',
      email: 'sales@industrialparts.com',
      phone: '555-0101',
      address: '100 Commerce St, Detroit, MI',
      categories: ['Machine Parts', 'Tools', 'Lubricants'],
      rating: 4.5,
      createdAt: daysAgo(365),
    },
    {
      id: uuidv4(),
      name: 'MedEquip Solutions',
      email: 'info@medequip.com',
      phone: '555-0202',
      address: '200 Healthcare Plaza, Boston, MA',
      categories: ['Medical Equipment', 'Consumables', 'Service'],
      rating: 4.8,
      createdAt: daysAgo(300),
    },
    {
      id: uuidv4(),
      name: 'HVAC Pro Services',
      email: 'support@hvacpro.com',
      phone: '555-0303',
      address: '300 Service Rd, Seattle, WA',
      categories: ['HVAC', 'Refrigeration', 'Electrical'],
      rating: 4.3,
      createdAt: daysAgo(400),
    },
  ]

  // RFQs
  const rfqs: RFQ[] = [
    {
      id: uuidv4(),
      title: 'Forklift Battery Replacement',
      description: 'Need quote for replacement battery for Toyota 8FG25 forklift',
      status: 'quoted',
      siteId: sites[0].id,
      requesterId: users[2].id,
      ticketId: tickets[1].id,
      dueDate: daysFromNow(5),
      supplierIds: [suppliers[0].id],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      id: uuidv4(),
      title: 'Annual HVAC Maintenance Contract',
      description: 'Requesting quotes for annual maintenance contract covering all HVAC units',
      status: 'sent',
      siteId: sites[2].id,
      requesterId: users[0].id,
      dueDate: daysFromNow(10),
      supplierIds: [suppliers[2].id],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(5),
    },
  ]

  // Quotes
  const quotes: Quote[] = [
    {
      id: uuidv4(),
      rfqId: rfqs[0].id,
      supplierId: suppliers[0].id,
      lines: [
        { id: uuidv4(), description: 'Toyota Forklift Battery 48V 500Ah', quantity: 1, unitPrice: 3200, total: 3200 },
        { id: uuidv4(), description: 'Installation and disposal', quantity: 1, unitPrice: 150, total: 150 },
      ],
      subtotal: 3350,
      tax: 268,
      total: 3618,
      leadTimeDays: 7,
      notes: 'Includes 2-year warranty. Installation scheduled within 3 days of delivery.',
      status: 'submitted',
      validUntil: daysFromNow(30),
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ]

  // POs
  const pos: PO[] = [
    {
      id: uuidv4(),
      poNumber: 'PO-2024-001',
      supplierId: suppliers[0].id,
      siteId: sites[0].id,
      requesterId: users[2].id,
      approverId: users[0].id,
      status: 'approved',
      lines: [
        { id: uuidv4(), description: 'Hydraulic Oil 5L (Case of 12)', quantity: 2, unitPrice: 480, total: 960 },
        { id: uuidv4(), description: 'Air Filter Set', quantity: 5, unitPrice: 85, total: 425 },
      ],
      subtotal: 1385,
      tax: 110.8,
      total: 1495.8,
      deliveryDate: daysFromNow(14),
      notes: 'Deliver to warehouse loading dock',
      approvalNotes: 'Approved - within budget',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(18),
      approvedAt: daysAgo(18),
      sentAt: daysAgo(18),
    },
  ]

  // Activities
  const activities: ActivityEvent[] = [
    {
      id: uuidv4(),
      entityType: 'ticket',
      entityId: tickets[0].id,
      userId: users[3].id,
      type: 'created',
      description: 'Ticket created',
      createdAt: tickets[0].createdAt,
    },
    {
      id: uuidv4(),
      entityType: 'ticket',
      entityId: tickets[0].id,
      userId: users[2].id,
      type: 'assigned',
      description: `Assigned to ${users[1].name}`,
      createdAt: daysAgo(0.8),
    },
    {
      id: uuidv4(),
      entityType: 'ticket',
      entityId: tickets[0].id,
      userId: users[1].id,
      type: 'status_changed',
      description: 'Status changed to In Progress',
      createdAt: daysAgo(0.5),
    },
  ]

  return {
    version: 1,
    users,
    sites,
    locations,
    tickets,
    comments: [],
    activities,
    attachments: [],
    assets,
    workOrders,
    pmPlans,
    suppliers,
    rfqs,
    quotes,
    pos,
    notifications: [],
    settings: {
      slaEnabled: true,
      slaPolicies: [
        { priority: 'low', responseMinutes: 240, resolutionMinutes: 2880 },
        { priority: 'medium', responseMinutes: 120, resolutionMinutes: 1440 },
        { priority: 'high', responseMinutes: 60, resolutionMinutes: 480 },
        { priority: 'critical', responseMinutes: 15, resolutionMinutes: 120 },
      ],
    },
    currentUserId: users[0].id,
  }
}
